version: "1.0"
services:
  web:
    image: nginx:latest
    volumes:
      - ./setup/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - frontend
      - backend
    ports:
      - "8081:80"

  frontend:
    image: node:latest
    volumes:
      - ./frontend:/app/frontend
    working_dir: /app/frontend
    command: sh -c "npm install && npm run dev"
    ports:
      - "8082:3000"
  
  backend:
    image: python:3.12

    volumes:
      - ./backend:/app/backend
    working_dir: /app/backend
    command: chmod +x ./backend/deploy/start.sh && ./backend/deploy/start.sh
    ports:
      - "8083:8000"